drop database if exists exam;
create database exam;

drop schema if exists book;
create schema book;

drop table if exists book.users;
create table book.users
(
    id       bigint generated by default as identity
        primary key,
    password varchar(255) not null,
    role     varchar(255),
    username varchar(255) not null
);

drop table if exists book.books;
create table book.books
(
    id     bigint generated by default as identity
        primary key,
    author varchar(255) not null,
    price  real         not null,
    title  varchar(255) not null
);

insert into book.users (username, password, role)
values ('admin', 'admin', 'ADMIN'),
       ('customer', 'customer', 'CUSTOMER');

insert into book.books (title, author, price)
values ('Otgan kunlar', 'Alisher Navoiy', 23.0),
       ('Mobi Dik', 'Sheroziy', 15.0),
       ('Little prince', 'Exupery', 10.0);